// Each row contains a word, then a binary Boolean indicating whether it should be pluralised
const nouns = [
['bananas',1],
['feminists',1],
['web development',0],
['sugar',0],
['magazines',1],
['football',0],
['parodies',1],
['articles',1],
['journalists',1],
['racism',0],
['sex work',0],
['polyamory',0],
['you',1],
['cars',1],
['charity',0],
['politicians',1],
['Brexit',0],
['abortions',1],
['ghosts',1],
['men',1],
['women',1],
['petrol',0],
['Barack Obama',0],
['Michelle Obama',0],
['Hillary Clinton',0],
['Donald Trump',0],
['Theresa May',0],
['JK Rowling',0],
['Harry Potter',0],
['Margaret Thatcher',0],
['Sylvia Plath',0],
['sex',0],
['pegging',0],
['vaginas',1],
['penises',1],
['blowjobs',1],
['lesbians',1],
['emoji',1],
['GamerGate',0],
['gaming',0],
['having an opinion',0],
['housework',0],
['Capitalism',0],
['waged labour',0],
['twitter',0],
['facebook',0],
['Gay Pride',0],
['sexting',0],
['having it all',0],
['selfies',1],
['weddings',1],
['cats',1],
['Halloween',0],
['colonialism',0],
['the Internet',0],
['celery',0],
['apologising',0],
['swearing',0],
['sport',0],
['despair',0],
['education',0],
['dancing',0],
['being white',0],
['reading',0],
['coffee',0],
['jogging',0],
['death',0],
['mermaids',1],
['science',0],
['doing laundry',0],
['flirting',0],
['skirts',1],
['tampons',1],
['periods',1],
['birth control',0],
['women\s equality',0],
['the wage gap',0],
['Black Lives Matter',0],
];
