const responses = [
'Interesting.',
'Maybe you should write a thinkpiece about it?',
'<b>🤔</b>',
'wow',
'deep',
'hmm',
'hmmmmmmmm&hellip;',
'Huh.',
'🤔 make u think',
'I bet Slate would be interested in 2,000 words on that topic.',
'Have you considered blogging about it?',
'Twitter needs to hear about this!',
'I wonder what your uncle on facebook thinks about it',
];
